build: dynamically generate flatc rust at compile time

diff --git a/.github/docker/Dockerfile.build b/.github/docker/Dockerfile.build
--- a/.github/docker/Dockerfile.build
+++ b/.github/docker/Dockerfile.build
@@ -1,16 +1,48 @@
-# Stage: Bonsol Test
+# Stage 1: flatc build
+FROM debian:stable-slim AS flatc-build
+RUN export DEBIAN_FRONTEND=noninteractive && \
+    apt-get update && \
+    apt-get install -y -q --no-install-recommends \
+    build-essential \
+    cmake \
+    ca-certificates \
+    curl \
+    git \
+    gnupg2 \
+    && \
+    apt-get clean && \
+    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
+
+# flatc
+WORKDIR /flatbuffers
+ARG FLATC_VERSION=24.3.25
+ADD https://github.com/google/flatbuffers/archive/refs/tags/v${FLATC_VERSION}.tar.gz v${FLATC_VERSION}.tar.gz
+RUN tar -zxvf v${FLATC_VERSION}.tar.gz || { echo "Failed to extract tarball"; exit 1; }
+WORKDIR /flatbuffers/flatbuffers-${FLATC_VERSION}
+RUN cmake -G "Unix Makefiles" && make -j && make install
+RUN strip /usr/local/bin/flatc
+
+# Stage 2: Bonsol Test
 FROM ghcr.io/anagrambuild/risczero:latest
+
+# flatbuffers
+COPY --from=flatc-build /usr/local/bin/flatc /usr/local/bin/flatc
+COPY --from=flatc-build /usr/local/include/flatbuffers /usr/local/include/flatbuffers
+COPY --from=flatc-build /usr/local/lib/libflatbuffers.a /usr/local/lib/libflatbuffers.a
+COPY --from=flatc-build /usr/local/lib/cmake/flatbuffers /usr/local/lib/cmake/flatbuffers
+COPY --from=flatc-build /usr/local/lib/pkgconfig/flatbuffers.pc /usr/local/lib/pkgconfig/flatbuffers.pc
+
 
 ENV USER=solana
 ARG SOLANA=1.18.22
 ENV CARGO_HOME=/usr/local/cargo
 ENV RUSTUP_HOME=/usr/local/rustup
-ENV PATH=${PATH}:/usr/local/cargo/bin:/go/bin:/home/solana/.local/share/solana/install/releases/${SOLANA}/bin
-USER solana
+ENV PATH=${PATH}:/usr/local/cargo/bin:/go/bin:/home/${USER}/.local/share/solana/install/releases/${SOLANA}/bin
 
 # Set user and working directory
 ARG PACKAGE=bonsol
 WORKDIR /workspaces/${PACKAGE}
+USER solana
 
 # Install Rust components
 RUN rustup component add \
@@ -19,9 +51,10 @@ RUN rustup component add \
 RUN rustup toolchain install nightly  && \
     rustup component add rustfmt --toolchain nightly
 
-COPY . .
+COPY --chown=${USER}:${USER} . .
 
 RUN /go/bin/yamlfmt -lint .github/workflows/*.yaml .github/workflows/*.yml .github/*.yaml .github/*.yml
 
+RUN cargo check
 RUN cargo +nightly fmt --all -- --check
 RUN cargo test   
